baseURL = "http://example.org/"
languageCode = "en-us"
theme = "cleanwhite"
title = "Shan van Rensburg"

[params]
    title_short = "SVR"
    slogan = "Web Developer | Lifelong Learner"
    header_image = "hero_svr.jpg"
    sidebar_avatar = "shan.png"